package FractalATE::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'FractalATE::DB',
    
    connect_info => {
        dsn => 'dbi:SQLite:/tmp/fractal.sqlite',
        user => '',
        password => '',
    }
);

=head1 NAME

FractalATE::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<FractalATE>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<FractalATE::DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.25

=head1 AUTHOR

David Dorward

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
